version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.01.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
            name: Install dependencies
            command: |
               apk update
               apk add curl
      - run:
          name: Install dependencies
          command: |
             curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
             chmod +x /usr/local/bin/docker-compose
             docker-compose -v
      - run:
          name: Build application Docker image
          command: |
            docker-compose build -c docker-compose.yaml 
      - deploy:
          name: Push application Docker image
          command: |
              docker tag k8s-wordsmith-db "${ECR_ENDPOINT}/k8s-wordsmith-db:${CIRCLE_SHA1}"
              docker tag k8s-wordsmith-db "${ECR_ENDPOINT}/k8s-wordsmith-db:${CIRCLE_SHA1}"
              docker tag k8s-wordsmith-db "${ECR_ENDPOINT}/k8s-wordsmith-db:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
